server:
  port: 9100

spring:
  h2:
    console:
      enabled: true
  datasource:
    jdbc-url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging.level.org.hibernate:
  SQL: debug
  type: TRACE
  type.descriptor:
    sql: trace